inc:
  # Blog Information
  title:        "unicone"
  # subtitle:     ""
  cover_image:  ""
  logo:         logo.png
  description: "A software consultancy. We find out what your business needs are and make it happen. So you can concentrate on growing your business."

  # Company information
  company:      unicone
  url:          http://unicone.com/
  about_link:   "/about"
  contact_link: "/contact"
  # facebook:   ""
  # twitter:    ""
  # gplus:      ""

  # Product Information
  # product_link: ""
  # tagline: ""

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  false

  # Sharing settings
  sharing:
    twitter:    false
    facebook:   false
    gplus:      false
    hn:         false

  # Analytics
  analytics:
    google: false # Add tracking code in _includes/_google-analytics.html

  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans:400,700'

  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

url:         http://unicone.com
source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
include:     ['.htaccess']
exclude:     []
timezone:    nil

# Show future posts
future:      false
show_drafts: nil
limit_posts: 0
highlighter: false

permalink:     pretty

markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true
